module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Golden',
    'Crystal',
    'Sunny',
    'Shady',
    'Blazing',
    'Hidden',
    'Wild',
    'Winding',
    'Eagle',
    'Howling',
    'Bear',
    'Moonlit',
    'Starlit',
    'Rocky',
    'Thunder',
    'Whispering',
    'Rustic',
    'Frozen',
    'Emerald',
    'Velvet',
    'Amber',
    'Boulder',
    'Cobalt',
    'Twilight',
    'Glowing',
    'Snowy',
    'Aurora',
    'Timber',
    'Shadow'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Meadow',
    'Peak',
    'Trail',
    'Pass',
    'Summit',
    'Wilderness',
    'Vista',
    'Cove',
    'Harbor',
    'Fjord',
    'Plateau',
    'Oasis',
    'Field',
    'Terrace',
    'Crag',
    'Valley',
    'Haven',
    'Grove',
    'Bluff',
    'Woodlands',
    'Overlook',
    'Highlands',
    'Ridge',
    'Chasm',
    'Fountain',
    'Basin',
    'Cairn',
    'Thicket',
    'Marsh',
    'Glade'
]

module.exports.phrases = [
    "Nestled in the heart of nature, this campground offers breathtaking views and tranquil surroundings.",
    "Experience serenity like never before with our secluded campsites under a canopy of stars.",
    "Perfect for adventurers, this site is surrounded by lush forests and winding trails.",
    "Relax by the crackling campfire and immerse yourself in the beauty of the great outdoors.",
    "A haven for nature enthusiasts, this location boasts stunning landscapes and abundant wildlife.",
    "Wake up to the sound of birdsong and the scent of fresh pine in this picturesque campground.",
    "Discover a hidden gem with unparalleled views and easy access to hiking and fishing spots.",
    "Reconnect with nature at this serene escape, offering endless opportunities for exploration.",
    "Unwind in the peaceful embrace of this campground, nestled near crystal-clear streams.",
    "A paradise for campers, this spot combines rustic charm with modern conveniences."
]
